name: ci
on: [push]

jobs:

  test:

    name: Test

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v1

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '24'
        
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli:  'latest'
          bb:   'latest'

      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
            ~/.npm
            .shadow-cljs
          key: cljdeps-${{ hashFiles('deps.edn') }}-${{ hashFiles ('package.json') }}-${{ hashFiles ('package-lock.json') }}
          restore-keys: cljdeps-

      - name: Fix git dubious directory ownership error
        run: git config --global --add safe.directory /__w/re-com/re-com

      - uses: browser-actions/setup-chrome@v1
        id: setup-chrome
        with:
          chrome-version: 811961

      - run: bb test :chrome-path '"${{ steps.setup-chrome.outputs.chrome-path }}"'

      - run: bb release-demo

      - uses: actions/upload-artifact@v4
        with:
          name: build-report
          path: target/build-report.html

      - name: Slack notification
        uses: homoluctus/slatify@v2.0.1
        if: failure() || cancelled()
        with:
          type: ${{ job.status  }}
          job_name: re-com Tests
          channel: '#oss-robots'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
